# Generated by Django 3.1.1 on 2020-11-23 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_auto_20201123_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='audio_file',
            new_name='file',
        ),
    ]
