# Generated by Django 3.1.1 on 2020-11-28 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0013_auto_20201127_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='speaker_file',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
