# Generated by Django 3.1.1 on 2021-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_auto_20210320_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Geography',
            field=models.CharField(choices=[('Beijing', 'Beijing'), ('Tianjin', 'Tianjin'), ('Shanghai', 'Shanghai'), ('Chongqing', 'Chongqing'), ('Hebei', 'Hebei'), ('Henan', 'Henan'), ('Yunnan', 'Yunnan'), ('Liaoning', 'Liaoning'), ('Heilongjiang', 'Heilongjiang'), ('Hunan', 'Hunan'), ('Anhui', 'Anhui'), ('Shandong', 'Shandong'), ('Xinjiang', 'Xinjiang'), ('Jiangsu', 'Jiangsu'), ('Zhejiang', 'Zhejiang'), ('Jiangxi', 'Jiangxi'), ('Hubei', 'Hubei'), ('Guangxi', 'Guangxi'), ('Gansu', 'Gansu'), ('Shanxi', 'Shanxi'), ('Inner Mongolia', 'Inner Mongolia'), ('Shaanxi', 'Shaanxi'), ('Jilin', 'Jilin'), ('Fujian', 'Fujian'), ('Guizhou', 'Guizhou'), ('Guangdong', 'Guangdong'), ('Qinghai', 'Qinghai'), ('Tibet', 'Tibet'), ('Sichuan', 'Sichuan'), ('Ningxia', 'Ningxia'), ('Hainan', 'Hainan'), ('Taiwan', 'Taiwan'), ('Hong Kong', 'Hong Kong'), ('Macao', 'Macao')], default='Beijing', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_type',
            field=models.CharField(choices=[('Huawei', 'Huawei'), ('Iphone', 'Iphone'), ('Samsung', 'Samsung'), ('Oppo', 'Oppo'), ('Vivo', 'Vivo'), ('Millet', 'Millet'), ('Redmi', 'Redmi')], default='Huawei', max_length=200),
        ),
    ]
