# Generated by Django 3.1.1 on 2020-11-09 02:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP', '0004_auto_20201108_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speech',
            new_name='Customer',
        ),
    ]
