# Generated by Django 3.1.1 on 2020-11-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_auto_20201123_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.FileField(null=True, upload_to='audio/'),
        ),
    ]
