# Generated by Django 3.1.1 on 2021-03-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_auto_20201128_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
