# Generated by Django 3.1.1 on 2021-03-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_auto_20210316_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='speaker_age',
            field=models.CharField(choices=[('<20', '<20'), ('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('>50', '>50')], default='20-40', max_length=200),
        ),
    ]
