# Generated by Django 3.1.1 on 2021-03-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_auto_20210321_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Geography',
            new_name='geography',
        ),
        migrations.AddField(
            model_name='customer',
            name='environment',
            field=models.CharField(choices=[('living room', 'living room'), ('restaurant', 'restaurant'), ('dormitory', 'dormitory'), ('bedroom', 'bedroom'), ('study', 'study')], default='living room', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_type',
            field=models.CharField(choices=[('Huawei', 'Huawei'), ('Iphone', 'Iphone'), ('Samsung', 'Samsung'), ('Oppo', 'Oppo'), ('Vivo', 'Vivo'), ('Millet', 'Millet'), ('other', 'other')], default='Huawei', max_length=200),
        ),
    ]
