# Generated by Django 3.1.1 on 2021-03-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_auto_20210323_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_type',
            field=models.CharField(choices=[('Huawei', 'Huawei'), ('Iphone', 'Iphone'), ('Samsung', 'Samsung'), ('Oppo', 'Oppo'), ('Vivo', 'Vivo'), ('Millet', 'Millet'), ('Other', 'Other')], default='Huawei', max_length=200),
        ),
    ]
