# Generated by Django 3.1.1 on 2021-03-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0019_auto_20210323_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='environment',
            field=models.CharField(choices=[('living room', 'living room'), ('restaurant', 'restaurant'), ('dormitory', 'dormitory'), ('bedroom', 'bedroom'), ('study', 'study'), ('Other', 'Other')], default='living room', max_length=200),
        ),
    ]
